import {
  Apple,
  Armchair,
  Baby,
  Banknote,
  Bed,
  Beer,
  Bike,
  Book,
  Briefcase,
  Building,
  Bus,
  Cake,
  Camera,
  Car,
  Cat,
  ChartPie,
  Coffee,
  Coins,
  CreditCard,
  Dog,
  Droplet,
  Dumbbell,
  Film,
  Fish,
  Flame,
  Fuel,
  Gamepad2,
  Gift,
  Glasses,
  Globe,
  GraduationCap,
  Hammer,
  Heart,
  HeartPulse,
  House,
  Key,
  Landmark,
  Laptop,
  Leaf,
  Lightbulb,
  Lock,
  MapPin,
  Monitor,
  Music,
  Package,
  Paintbrush,
  PartyPopper,
  Phone,
  PiggyBank,
  Pill,
  Pizza,
  Plane,
  Plug,
  Receipt,
  Scissors,
  Shield,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Snowflake,
  Sparkles,
  Star,
  Stethoscope,
  Sun,
  Tag,
  Ticket,
  TrainFront,
  TrendingDown,
  TrendingUp,
  Tv,
  Umbrella,
  Users,
  Utensils,
  Wallet,
  Watch,
  Wifi,
  Wine,
  Wrench,
  type LucideIcon,
} from 'lucide-react'

export interface CategoryIconDef {
  /** Nome kebab-case guardado na base de dados (nome lucide). */
  name: string
  /** Etiqueta em português, usada na pesquisa do seletor. */
  label: string
  Icon: LucideIcon
}

export const CATEGORY_ICONS: CategoryIconDef[] = [
  { name: 'shopping-cart', label: 'Carrinho de compras', Icon: ShoppingCart },
  { name: 'shopping-bag', label: 'Saco de compras', Icon: ShoppingBag },
  { name: 'utensils', label: 'Restaurante', Icon: Utensils },
  { name: 'coffee', label: 'Café', Icon: Coffee },
  { name: 'pizza', label: 'Pizza', Icon: Pizza },
  { name: 'beer', label: 'Cerveja', Icon: Beer },
  { name: 'wine', label: 'Vinho', Icon: Wine },
  { name: 'cake', label: 'Bolo', Icon: Cake },
  { name: 'apple', label: 'Fruta', Icon: Apple },
  { name: 'fish', label: 'Peixe', Icon: Fish },
  { name: 'car', label: 'Carro', Icon: Car },
  { name: 'bus', label: 'Autocarro', Icon: Bus },
  { name: 'train-front', label: 'Comboio', Icon: TrainFront },
  { name: 'plane', label: 'Avião', Icon: Plane },
  { name: 'bike', label: 'Bicicleta', Icon: Bike },
  { name: 'fuel', label: 'Combustível', Icon: Fuel },
  { name: 'house', label: 'Casa', Icon: House },
  { name: 'building', label: 'Prédio', Icon: Building },
  { name: 'bed', label: 'Cama', Icon: Bed },
  { name: 'armchair', label: 'Mobília', Icon: Armchair },
  { name: 'lightbulb', label: 'Eletricidade', Icon: Lightbulb },
  { name: 'plug', label: 'Energia', Icon: Plug },
  { name: 'droplet', label: 'Água', Icon: Droplet },
  { name: 'flame', label: 'Gás', Icon: Flame },
  { name: 'wifi', label: 'Internet', Icon: Wifi },
  { name: 'phone', label: 'Telefone', Icon: Phone },
  { name: 'smartphone', label: 'Telemóvel', Icon: Smartphone },
  { name: 'laptop', label: 'Portátil', Icon: Laptop },
  { name: 'monitor', label: 'Computador', Icon: Monitor },
  { name: 'tv', label: 'Televisão', Icon: Tv },
  { name: 'gamepad-2', label: 'Videojogos', Icon: Gamepad2 },
  { name: 'music', label: 'Música', Icon: Music },
  { name: 'film', label: 'Cinema', Icon: Film },
  { name: 'party-popper', label: 'Festa', Icon: PartyPopper },
  { name: 'ticket', label: 'Bilhetes', Icon: Ticket },
  { name: 'camera', label: 'Fotografia', Icon: Camera },
  { name: 'dumbbell', label: 'Ginásio', Icon: Dumbbell },
  { name: 'heart-pulse', label: 'Saúde', Icon: HeartPulse },
  { name: 'stethoscope', label: 'Médico', Icon: Stethoscope },
  { name: 'pill', label: 'Farmácia', Icon: Pill },
  { name: 'baby', label: 'Bebé', Icon: Baby },
  { name: 'dog', label: 'Cão', Icon: Dog },
  { name: 'cat', label: 'Gato', Icon: Cat },
  { name: 'shirt', label: 'Roupa', Icon: Shirt },
  { name: 'watch', label: 'Relógio', Icon: Watch },
  { name: 'glasses', label: 'Óculos', Icon: Glasses },
  { name: 'scissors', label: 'Cabeleireiro', Icon: Scissors },
  { name: 'sparkles', label: 'Beleza', Icon: Sparkles },
  { name: 'gift', label: 'Presentes', Icon: Gift },
  { name: 'graduation-cap', label: 'Educação', Icon: GraduationCap },
  { name: 'book', label: 'Livros', Icon: Book },
  { name: 'briefcase', label: 'Trabalho', Icon: Briefcase },
  { name: 'banknote', label: 'Dinheiro', Icon: Banknote },
  { name: 'coins', label: 'Moedas', Icon: Coins },
  { name: 'piggy-bank', label: 'Poupança', Icon: PiggyBank },
  { name: 'wallet', label: 'Carteira', Icon: Wallet },
  { name: 'credit-card', label: 'Cartão', Icon: CreditCard },
  { name: 'landmark', label: 'Banco', Icon: Landmark },
  { name: 'trending-up', label: 'Investimentos', Icon: TrendingUp },
  { name: 'trending-down', label: 'Perdas', Icon: TrendingDown },
  { name: 'chart-pie', label: 'Orçamento', Icon: ChartPie },
  { name: 'receipt', label: 'Recibo', Icon: Receipt },
  { name: 'package', label: 'Encomendas', Icon: Package },
  { name: 'wrench', label: 'Reparações', Icon: Wrench },
  { name: 'hammer', label: 'Obras', Icon: Hammer },
  { name: 'paintbrush', label: 'Pintura', Icon: Paintbrush },
  { name: 'leaf', label: 'Natureza', Icon: Leaf },
  { name: 'sun', label: 'Férias', Icon: Sun },
  { name: 'snowflake', label: 'Inverno', Icon: Snowflake },
  { name: 'umbrella', label: 'Seguro', Icon: Umbrella },
  { name: 'shield', label: 'Proteção', Icon: Shield },
  { name: 'lock', label: 'Segurança', Icon: Lock },
  { name: 'key', label: 'Renda', Icon: Key },
  { name: 'map-pin', label: 'Viagens', Icon: MapPin },
  { name: 'globe', label: 'Estrangeiro', Icon: Globe },
  { name: 'users', label: 'Família', Icon: Users },
  { name: 'heart', label: 'Amor', Icon: Heart },
  { name: 'star', label: 'Favoritos', Icon: Star },
  { name: 'tag', label: 'Etiqueta', Icon: Tag },
]

const byName = new Map(CATEGORY_ICONS.map((d) => [d.name, d.Icon]))

/** Devolve o componente do ícone; desconhecido → etiqueta genérica. */
export function getCategoryIcon(name: string | undefined | null): LucideIcon {
  return (name && byName.get(name)) || Tag
}
